"""Make admin_id in clerks nullable and set ondelete to SET NULL

Revision ID: 1cdb57c155c7
Revises: 
Create Date: 2025-07-18 17:34:03.068070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdb57c155c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clerks', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('clerks_admin_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admins', ['admin_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clerks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('clerks_admin_id_fkey', 'admins', ['admin_id'], ['id'])
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
