"""Add Store model and store_id to Admin/Clerk, with SET NULL ondelete

Revision ID: b8b8843af281
Revises: 1cdb57c155c7
Create Date: 2025-07-18 17:54:51.455298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b8843af281'
down_revision = '1cdb57c155c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('clerks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clerks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('store_id')

    # ### end Alembic commands ###
